# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    jamjar.service:
            class: AppBundle\Service\JamJarService
            autowire: true

    admin.jamjar:
            class: AppBundle\Admin\JamJarAdmin
            arguments: [~, AppBundle\Entity\JamJar, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: JamJar }
            calls:
                - [ getJamJarService, ['@jamjar.service']]

    admin.jamtype:
            class: AppBundle\Admin\JamTypeAdmin
            arguments: [~, AppBundle\Entity\JamType, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: JamType }

    admin.jamYear:
              class: AppBundle\Admin\JamYearAdmin
              arguments: [~, AppBundle\Entity\Year, ~]
              tags:
                  - { name: sonata.admin, manager_type: orm, label: JamYear }
